[package]
authors = ["The Knurling-rs developers"]
categories = ["embedded", "no-std"]
description = "A highly efficient logging framework that targets resource-constrained devices, like microcontrollers"
edition = "2018"
keywords = ["knurling", "logging", "formatting"]
license = "MIT OR Apache-2.0"
links = "defmt" # Prevent multiple versions of defmt being linked
name = "defmt"
readme = "README.md"
repository = "https://github.com/knurling-rs/defmt"
version = "0.1.3"

[features]
alloc = []

# WARNING: for internal use only, not covered by semver guarantees
unstable-test = ["defmt-macros/unstable-test"]

[dependencies]
defmt-macros = { path = "macros", version = "0.1.1" }
heapless = "0.5.6"

[dev-dependencies]
rustc_version = "0.3.0"
trybuild = "1.0.37"

[workspace]
members = [
  ".",
  "decoder",
  "elf2table",
  "logger",
  "macros",
  "parser",
  "print",
  "qemu-run",
  "firmware/*",
]

[profile.release]
codegen-units = 1
debug = 2
debug-assertions = false
incremental = false
lto = "fat"
opt-level = 3
overflow-checks = false

[build-dependencies]
semver = "0.11.0"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = [ "--cfg=docsrs" ]
targets = ["thumbv6m-none-eabi", "thumbv7em-none-eabihf"]
