[package]
authors = ["The Knurling-rs developers"]
edition = "2018"
license = "MIT OR Apache-2.0"
name = "defmt-test"
version = "0.1.0"

[dependencies]
cortex-m = "0.6.3"
cortex-m-rt = "0.6.13"
defmt-test-macros = { path = "macros" }

[dependencies.defmt]
git = "https://github.com/knurling-rs/defmt"
branch = "main"
