[package]
authors = ["The Knurling-rs developers"]
edition = "2018"
license = "MIT OR Apache-2.0"
name = "qemu-run"
publish = false
version = "0.2.0"

[dependencies]
anyhow = "1.0.40"
defmt-decoder = { path = "../decoder", features = ["unstable"], version = "=0.2.1" }
