[package]
authors = ["The Knurling-rs developers"]
edition = "2021"
license = "MIT OR Apache-2.0"
name = "defmt-semihosting"
version = "0.1.0"

[dependencies]
defmt = { version = "0.3", path = "../../defmt" }
cortex-m = "0.7"
cortex-m-semihosting = "0.5"
