[package]
authors = ["The Knurling-rs developers"]
edition = "2018"
keywords = ["knurling", "defmt"]
license = "MIT OR Apache-2.0"
name = "defmt-parser"
readme = "../README.md"
repository = "https://github.com/knurling-rs/defmt"
version = "0.1.0"

[features]
unstable = []

[package.metadata.docs.rs]
features = ["unstable"]
rustdoc-args = [ "--cfg=docsrs" ]
