[package]
authors = ["The Knurling-rs developers"]
description = "Decodes defmt log frames"
edition = "2018"
keywords = ["knurling", "defmt"]
license = "MIT OR Apache-2.0"
name = "defmt-decoder"
readme = "../README.md"
repository = "https://github.com/knurling-rs/defmt"
version = "0.2.2"

[dependencies]
defmt-parser = { path = "../parser", features = ["unstable"], version = "=0.2.2" }
byteorder = "1"
colored = "2.0"
ryu = "1"

# logger
difference = "2.0"
log = { version = "0.4", features = ["std"] }

# elf2table
anyhow = "1.0"
gimli = { version = "0.24", default-features = false, features = ["read", "std"] }
object = { version = "0.25", default-features = false, features = ["read_core", "elf", "std"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[features]
# WARNING: API and wire format subject to change.
unstable = []

[package.metadata.docs.rs]
features = ["unstable"]
rustdoc-args = [ "--cfg=docsrs" ]
