[package]
authors = ["The Knurling-rs developers"]
description = "Decodes defmt log frames"
edition = "2018"
keywords = ["knurling", "defmt"]
license = "MIT OR Apache-2.0"
name = "defmt-decoder"
readme = "../README.md"
repository = "https://github.com/knurling-rs/defmt"
version = "0.1.4"

[dependencies]
defmt-parser = { path = "../parser", features = ["unstable"], version = "0.1.0" }
byteorder = "1"
colored = "2.0.0"
leb128 = "0.2.4"
ryu = "1"

[build-dependencies]
semver = "0.11.0"

[features]
# WARNING: API and wire format subject to change.
unstable = []

[package.metadata.docs.rs]
features = ["unstable"]
rustdoc-args = [ "--cfg=docsrs" ]
