[package]
authors = ["The Knurling-rs developers"]
edition = "2018"
license = "MIT OR Apache-2.0"
name = "defmt-macros"
version = "0.1.0"

[lib]
proc-macro = true

[dependencies]
defmt-parser = { path = "../parser" }
quote = "1.0.7"
proc-macro2 = "1.0.18"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[dependencies.syn]
features = ["full"]
version = "1.0.31"
