[package]
authors = ["The Knurling-rs developers"]
description = "defmt macros"
edition = "2018"
keywords = ["knurling", "defmt"]
license = "MIT OR Apache-2.0"
name = "defmt-macros"
readme = "../README.md"
repository = "https://github.com/knurling-rs/defmt"
version = "0.1.1"

[lib]
proc-macro = true

[features]
# WARNING: for internal use only, not covered by semver guarantees
unstable-test = []

[dependencies]
defmt-parser = { path = "../parser", features = ["unstable"], version = "0.1.0" }
quote = "1.0.7"
proc-macro2 = "1.0.18"

[dependencies.syn]
features = ["full"]
version = "1.0.31"
